import { writeFile } from "node:fs/promises";
import { stringify } from "yaml";
import type { CitadelConfig } from "../../schemas/citadel.js";
import type { MaesterConfig } from "../../schemas/maester.js";
import { citadelConfigPath, maesterConfigPath } from "./paths.js";

const CITADEL_HEADER = `# citadel.yaml
#
# This file declares the remote knowledge sources this repository pulls into
# a local destination directory.
#
# Each source is a git repository. By default, the citadel fetches whatever
# the source publishes in its own \`maester.yaml\` manifest. If a source does
# not publish a manifest (or you want to override what gets pulled), declare
# an \`includes\` list and the citadel will materialize exactly those paths
# or globs instead.
#
# By default, every source is surfaced at \`<baseDir>/<source-name>/\` from the
# repository root. The optional top-level \`baseDir\` field changes that parent
# folder once for every source; when omitted, the default is \`citadel\`. A
# per-source \`destination\` always wins over the configured base.
#
# Run \`maester sync\` (or \`npm run maester:sync\`) to refresh every source in
# one pass. Generated by \`npx maester init\` and safe to commit. Secret
# values are never stored here — only the names of environment variables
# that hold them.

`;

const MAESTER_HEADER = `# maester.yaml
#
# This file declares the documents this repository publishes to any citadel
# that pulls from it. It is a manifest only — the documents themselves live
# wherever the \`path\` fields point, and \`maester\` does not modify them.
#
# Generated by \`npx maester publish\` and safe to commit.

`;

export async function writeCitadelConfig(repoRoot: string, config: CitadelConfig): Promise<string> {
  const path = citadelConfigPath(repoRoot);
  const ordered = {
    schemaVersion: config.schemaVersion,
    ...(config.baseDir ? { baseDir: config.baseDir } : {}),
    sources: config.sources,
    ...(config.connectors && config.connectors.length > 0 ? { connectors: config.connectors } : {}),
  };
  const body = stringify(ordered, { indent: 2, lineWidth: 100, singleQuote: false });
  await writeFile(path, `${CITADEL_HEADER}${body}`, "utf8");
  return path;
}

export async function writeMaesterConfig(repoRoot: string, config: MaesterConfig): Promise<string> {
  const path = maesterConfigPath(repoRoot);
  const body = stringify(config, { indent: 2, lineWidth: 100, singleQuote: false });
  await writeFile(path, `${MAESTER_HEADER}${body}`, "utf8");
  return path;
}
