import { writeFile } from "node:fs/promises";
import { stringify } from "yaml";
import type { CitadelConfig } from "../../schemas/citadel.js";
import type { MaesterConfig } from "../../schemas/maester.js";
import { citadelConfigPath, maesterConfigPath } from "./paths.js";

const CITADEL_HEADER = `# citadel.yaml
#
# This file declares the remote knowledge sources this repository pulls into
# its local \`citadel/\` directory. Two kinds of sources are supported:
#
#   * maesters — repositories that publish their own \`maester.yaml\` declaring
#     what they make available. The citadel consumes whatever the maester
#     publishes; the maester owns the publish surface.
#   * ravens — git repositories the citadel pulls from without any manifest
#     on the remote side. The citadel itself declares the \`includes\` list of
#     paths/globs to materialize. Use ravens for public third-party repos or
#     private repos you have read access to but do not own.
#
# Run \`maester sync\` (or \`npm run maester:sync\`) to refresh both kinds in
# one pass. Generated by \`npx maester init\` and safe to commit. Secret
# values are never stored here — only the names of environment variables
# that hold them.

`;

const MAESTER_HEADER = `# maester.yaml
#
# This file declares the documents this repository publishes to any citadel
# that pulls from it. It is a manifest only — the documents themselves live
# wherever the \`path\` fields point, and \`maester\` does not modify them.
#
# Generated by \`npx maester publish\` and safe to commit.

`;

export async function writeCitadelConfig(repoRoot: string, config: CitadelConfig): Promise<string> {
  const path = citadelConfigPath(repoRoot);
  // Emit a stable field order: schemaVersion, then maesters, then ravens.
  const ordered = {
    schemaVersion: config.schemaVersion,
    maesters: config.maesters,
    ravens: config.ravens,
  };
  const body = stringify(ordered, { indent: 2, lineWidth: 100, singleQuote: false });
  await writeFile(path, `${CITADEL_HEADER}${body}`, "utf8");
  return path;
}

export async function writeMaesterConfig(repoRoot: string, config: MaesterConfig): Promise<string> {
  const path = maesterConfigPath(repoRoot);
  const body = stringify(config, { indent: 2, lineWidth: 100, singleQuote: false });
  await writeFile(path, `${MAESTER_HEADER}${body}`, "utf8");
  return path;
}
