import CITADEL_AWARENESS from "../content/citadel-awareness.md";
import FRESHNESS_AWARENESS from "../content/freshness-awareness.md";
import STATE_AWARENESS from "../content/state-awareness.md";

const PREAMBLE = `# AGENTS.md

This file contains agent instructions for working in this repository. The
section between the maester managed-region markers is generated by
\`maester skill install\` and refreshed by \`maester skill upgrade\`. Anything
you write outside that region is preserved across upgrades.
`;

export function renderAgentsMdBody(opts: { baseDir: string }): string {
  return [
    "# Grand Maester guidance",
    "",
    "This repository is set up to aggregate documentation from remote sources",
    "into a local citadel. When you reason about citadel content, follow the",
    "guidance below.",
    "",
    interpolate(CITADEL_AWARENESS, opts),
    "",
    interpolate(STATE_AWARENESS, opts),
    "",
    interpolate(FRESHNESS_AWARENESS, opts),
  ].join("\n");
}

export function agentsMdPreamble(): string {
  return PREAMBLE;
}

function interpolate(template: string, opts: { baseDir: string }): string {
  return template.replace(/\{\{baseDir\}\}/g, opts.baseDir);
}
